# Generated by Django 5.2.3 on 2025-07-04 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('party', models.CharField(default='', max_length=100)),
                ('position', models.CharField(default='', max_length=100)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('is_faculty_representative', models.BooleanField(default=True)),
                ('faculty', models.CharField(blank=True, choices=[('Engineering', 'Engineering'), ('Arts', 'Arts'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Law', 'Law'), ('Medicine', 'Medicine')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('constituency', models.CharField(blank=True, max_length=100, null=True)),
                ('has_voted', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('faculty', models.CharField(blank=True, choices=[('Engineering', 'Engineering'), ('Arts', 'Arts'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Law', 'Law'), ('Medicine', 'Medicine')], max_length=50, null=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_voters', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_voters', to=settings.AUTH_USER_MODEL)),
                ('voted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voted_voters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evoting.candidate')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evoting.voter')),
            ],
        ),
    ]
