# Generated by Django 5.2.3 on 2025-07-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evoting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='constituency',
        ),
        migrations.AddField(
            model_name='voter',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='faculty',
            field=models.CharField(blank=True, choices=[('Engineering', 'Engineering'), ('Arts', 'Arts'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Law', 'Law'), ('Medicine', 'Medicine'), ('Education', 'Education'), ('All', 'All Faculties')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='age',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='faculty',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Arts', 'Arts'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Law', 'Law'), ('Medicine', 'Medicine'), ('Education', 'Education'), ('All', 'All Faculties')], max_length=50),
        ),
    ]
