# Generated by Django 5.2.3 on 2025-06-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evoting', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.CharField(default='', max_length=100),
        ),
    ]
