# Generated by Django 5.2.3 on 2025-07-19 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evoting', '0002_remove_voter_constituency_voter_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
