# Generated by Django 5.2.3 on 2025-07-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evoting', '0003_alter_voter_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
