# Generated by Django 5.2.3 on 2025-07-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evoting', '0005_candidate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
