# Generated by Django 5.2.3 on 2025-07-22 09:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evoting', '0007_alter_candidate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='photo_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
