# Generated by Django 5.2.3 on 2025-06-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evoting', '0008_rename_timestamp_vote_voted_at_alter_vote_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
