# Generated by Django 5.2.3 on 2025-06-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evoting', '0009_voter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='faculty',
            field=models.CharField(blank=True, choices=[('Engineering', 'Engineering'), ('Arts', 'Arts'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Law', 'Law'), ('Medicine', 'Medicine')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='faculty',
            field=models.CharField(blank=True, choices=[('Engineering', 'Engineering'), ('Arts', 'Arts'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Law', 'Law'), ('Medicine', 'Medicine')], max_length=50, null=True),
        ),
    ]
