# Generated by Django 5.2.3 on 2025-06-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evoting', '0010_candidate_faculty_voter_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_faculty_representative',
            field=models.BooleanField(default=True),
        ),
    ]
